echo "# macOS 15.6.1
https://updates.cdn-apple.com/2025SummerFCS/fullrestores/093-10809/CFD6DD38-DAF0-40DA-854F-31AAD1294C6F/UniversalMac_15.6.1_24G90_Restore.ipsw" >> /Users/arcomputers/Downloads/macAll-main/T2.md
